name: Vercel Production Deployment

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - public/**
      - package.json
      - svelte.config.js
      - tsconfig.json
      - .node-version
      - .github/workflows/deploy-vercel-prod.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: true
