name: Vercel Preview Deployment

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ENV: preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm install
      - name: Bump version
        id: package_version
        uses: KageKirin/bump-node-package-version@v0
        with:
          patch: true
      - name: Replace version in package.json
        run: |
          echo "Bumping version to ${{ steps.package_version.outputs.version }}"
          jq '.version = "${{ steps.package_version.outputs.version }}"' > tmp.json && mv tmp.json package.json
      - name: Install Vercel CLI
        run: |
          npm install --global vercel@latest vite@latest
      - name: Pull environment
        run: |
          vercel pull --yes --environment=${{ env.VERCEL_ENV }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: |
          cat package.json
          vercel build --yes --target=${{ env.VERCEL_ENV }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to ${{ env.VERCEL_ENV }} environment
        run: |
          vercel deploy --yes --prebuilt --target=${{ env.VERCEL_ENV }} --token=${{ secrets.VERCEL_TOKEN }}
